services:
  gateway:
    image: nitsvutt/gateway:1.0.0
    hostname: gateway
    ports:
      - "8977:8977"
    volumes:
      - ../workspace:/project
    environment:
      - SPARK_MODE=client
    command: jupyter notebook --no-browser --NotebookApp.token 'password' --ip 0.0.0.0 --port 8977 --allow-root
    networks:
      - iceberg_lakehouse_platform

networks:
  iceberg_lakehouse_platform:
    external: true