version: "3.5"
services:
  spark-master:
    image: nitsvutt/spark-3.4.1-hadoop3:arm
    hostname: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - $COMMON_PATH/spark_logs:/opt/spark-events
       - $COMMON_PATH/spark_apps:/opt/spark-apps
    environment:
      - SPARK_MODE=master
    networks:
      - iceberg_lakehouse_platform

  spark-history-server:
    image: nitsvutt/spark-3.4.1-hadoop3:arm
    hostname: spark-history-server
    ports:
      - "19090:18080"
    depends_on:
      - spark-master
    volumes:
       - $COMMON_PATH/spark_logs:/opt/spark-events
       - $COMMON_PATH/spark_apps:/opt/spark-apps
    environment:
      - SPARK_MODE=history
    networks:
      - iceberg_lakehouse_platform

  spark-worker-1:
    image: nitsvutt/spark-3.4.1-hadoop3:arm
    hostname: spark-worker-1
    ports:
      - "9091:8081"
      - "7001:7000"
    depends_on:
      - spark-master
    volumes:
       - $COMMON_PATH/spark_logs:/opt/spark-events
       - $COMMON_PATH/spark_apps:/opt/spark-apps
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    networks:
      - iceberg_lakehouse_platform

  spark-worker-2:
    image: nitsvutt/spark-3.4.1-hadoop3:arm
    hostname: spark-worker-2
    ports:
      - "9092:8081"
      - "7002:7000"
    depends_on:
      - spark-master
    volumes:
       - $COMMON_PATH/spark_logs:/opt/spark-events
       - $COMMON_PATH/spark_apps:/opt/spark-apps
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    networks:
      - iceberg_lakehouse_platform

networks:
  iceberg_lakehouse_platform:
    external: true