services:
  mysql:
    image: mysql:8.3.0
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - $COMMON_PATH/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=product2
    restart: always
    networks:
      - iceberg_lakehouse_platform

  product2:
    image: nitsvutt/fastapi-python:3.10.4
    hostname: product2
    depends_on:
      - mysql
    ports:
      - "8902:8902"
    volumes:
      - .:/app
    environment:
      MYSQL_SERVER: $MYSQL_SERVER
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    command: uvicorn main:product2 --host 0.0.0.0 --port 8902 --reload
    networks:
      - iceberg_lakehouse_platform

networks:
  iceberg_lakehouse_platform:
    external: true