services:
  mysql:
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - $COMMON/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=product2