services:
  namenode:
    image: nitsvutt/hadoop:3.3.6
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - $COMMON_PATH/hadoop/namenode:/hadoop/dfs/name
    environment:
      - HADOOP_MODE=namenode
    networks:
      - lakehouse_platform

  datanode1:
    image: nitsvutt/hadoop:3.3.6
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - $COMMON_PATH/hadoop/datanode1:/hadoop/dfs/data
    environment:
      - HADOOP_MODE=datanode
    networks:
      - lakehouse_platform
  
  datanode2:
    image: nitsvutt/hadoop:3.3.6
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - $COMMON_PATH/hadoop/datanode2:/hadoop/dfs/data
    environment:
      - HADOOP_MODE=datanode
    networks:
      - lakehouse_platform
  
  datanode3:
    image: nitsvutt/hadoop:3.3.6
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - $COMMON_PATH/hadoop/datanode3:/hadoop/dfs/data
    environment:
      - HADOOP_MODE=datanode
    networks:
      - lakehouse_platform

  resourcemanager:
    image: nitsvutt/hadoop:3.3.6
    container_name: resourcemanager
    ports:
      - 8088:8088
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    environment:
      - HADOOP_MODE=resourcemanager
    networks:
      - lakehouse_platform

  nodemanager:
    image: nitsvutt/hadoop:3.3.6
    container_name: nodemanager
    ports:
      - 8042:8042
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    environment:
      - HADOOP_MODE=nodemanager
    networks:
      - lakehouse_platform
  
  timelineserver:
    image: nitsvutt/hadoop:3.3.6
    container_name: timelineserver
    ports:
      - 8188:8188
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    environment:
      - HADOOP_MODE=timelineserver
    volumes:
      - $COMMON_PATH/hadoop/timelineserver:/hadoop/yarn/timeline
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true