services:
  postgresql:
    image: postgres:15-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - $COMMON/postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_DB=product1